# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

    # Publish `v1.2.3` tags as releases.
    #tags:
    #  - v*

    paths-ignore:
      - '**.md'
      - '*/whatsnew-en-US'

env:
  # Name of docker image
  IMAGE_NAME: nextcloud-nginx-proxy

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-web:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Allow unsecure commands 🤦
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # required for dokku
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.1
      with:
         node-version: '14'

    - name: Build image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME

  publish-web:
    needs: build-web

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # we only push tags to kubernetes
    # if: startsWith(github.ref, 'refs/tags/v') # for now we will just push latest

    # steps to push to kube
    steps:

    # check out the files, we need them to get the k8 ymls
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # required for dokku

    - name: Push to Dokku
      uses: dokku/github-action@v1.1.2
      with:
        git_remote_url: 'ssh://dokku@bubblelabs.dev:22/nc-proxy'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
